apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: solargrid-project
  namespace: argocd
spec:
  description: Project for solar panel defect detection applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: solar-panel-detection
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
