apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solargrid-defect-detection
  namespace: argocd
spec:
  project: solargrid-project
  source:
    repoURL: https://github.com/yourusername/solar-farm-defect-detection
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: solar-panel-detection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  # This section helps handle the storage class differences between environments
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/storageClassName
    - /spec/volumeMode
