apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
reclaimPolicy: Delete
volumeBindingMode: Immediate
