apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-model-storage
  namespace: solar-panel-detection
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-standard
  resources:
    requests:
      storage: 5Gi
