apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: solar-panel-detection
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk-standard
  resources:
    requests:
      storage: 5Gi
