apiVersion: v1
kind: Service
metadata:
  name: microcontroller-interface
  namespace: solar-panel-detection
spec:
  selector:
    app: microcontroller-simulator
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: solar-panel-detection
spec:
  selector:
    app: mqtt-broker
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: websocket
    port: 9001
    targetPort: 9001
  type: ClusterIP
