# manifests/supportingservice/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: solar-panel-detection
spec:
  selector:
    app: api-server
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
  type: NodePort  # Changed from LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ai-processor-service
  namespace: solar-panel-detection
  labels:
    app: ai-processor
spec:
  selector:
    app: ai-processor
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 9102
    targetPort: 9102
    name: metrics
  type: ClusterIP
